# Generated by Django 5.1.1 on 2024-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_prep',
            field=models.TextField(default='there is no data on this item'),
        ),
    ]
